services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    volumes:
      - .:/app
      - discord-data:/app/data
    working_dir: /app
    command: python3 main.py

# Volume for storing persistent data
volumes:
  discord-data:
    name: discord-data
